from __future__ import annotations

from .comparison_analysis import (
    aggregate_method_hits,
    aggregate_variant_hits,
    build_category_portraits,
    build_category_sample_index,
    build_failure_clusters,
    build_failure_reason_clusters,
    build_markdown_category_portraits,
    build_rankings,
    build_recommendation_checklist,
    build_risk_categories,
    build_sample_ref,
    build_stable_failure_lines,
    build_summary_insights,
    build_trend_lines,
    compare_summary_rows,
    format_sample_refs_inline,
    make_check,
    normalize_failure_reason,
    prioritize_checks,
    render_html_sample_refs_inline,
    render_markdown_failure_clusters,
    render_markdown_risk_categories,
    summarize_comparison_delta,
    top_method_check,
    top_variant_check,
    build_comparison_report_context,
)
from .comparison_charts import (
    build_report_chart_paths,
    compute_chart_figure_height,
    create_comparison_bar_chart,
    create_comparison_grouped_bar_chart,
    generate_comparison_charts,
)
from .comparison_html import (
    build_comparison_html_report,
    render_category_portrait_cards,
    render_html_failure_clusters,
    render_html_risk_categories,
)
from .comparison_markdown import build_comparison_markdown_report

__all__ = [
    "aggregate_method_hits",
    "aggregate_variant_hits",
    "build_category_portraits",
    "build_category_sample_index",
    "build_comparison_html_report",
    "build_comparison_markdown_report",
    "build_comparison_report_context",
    "build_failure_clusters",
    "build_failure_reason_clusters",
    "build_markdown_category_portraits",
    "build_rankings",
    "build_recommendation_checklist",
    "build_report_chart_paths",
    "build_risk_categories",
    "build_sample_ref",
    "build_stable_failure_lines",
    "build_summary_insights",
    "build_trend_lines",
    "compare_summary_rows",
    "compute_chart_figure_height",
    "create_comparison_bar_chart",
    "create_comparison_grouped_bar_chart",
    "format_sample_refs_inline",
    "generate_comparison_charts",
    "make_check",
    "normalize_failure_reason",
    "prioritize_checks",
    "render_category_portrait_cards",
    "render_html_failure_clusters",
    "render_html_risk_categories",
    "render_html_sample_refs_inline",
    "render_markdown_failure_clusters",
    "render_markdown_risk_categories",
    "summarize_comparison_delta",
    "top_method_check",
    "top_variant_check",
]
