from __future__ import annotations

from .comparison_checklists import (
    build_recommendation_checklist,
    make_check,
    prioritize_checks,
    top_method_check,
    top_variant_check,
)
from .comparison_diagnostics import (
    build_category_portraits,
    build_comparison_report_context,
    build_failure_clusters,
    build_failure_reason_clusters,
    build_markdown_category_portraits,
    build_stable_failure_lines,
    build_trend_lines,
    normalize_failure_reason,
    render_markdown_failure_clusters,
    render_markdown_risk_categories,
)
from .comparison_metrics import (
    aggregate_method_hits,
    aggregate_variant_hits,
    build_category_sample_index,
    build_rankings,
    build_risk_categories,
    build_sample_ref,
    build_summary_insights,
    compare_summary_rows,
    format_sample_refs_inline,
    render_html_sample_refs_inline,
    summarize_comparison_delta,
)

__all__ = [
    "aggregate_method_hits",
    "aggregate_variant_hits",
    "build_category_portraits",
    "build_category_sample_index",
    "build_comparison_report_context",
    "build_failure_clusters",
    "build_failure_reason_clusters",
    "build_markdown_category_portraits",
    "build_rankings",
    "build_recommendation_checklist",
    "build_risk_categories",
    "build_sample_ref",
    "build_stable_failure_lines",
    "build_summary_insights",
    "build_trend_lines",
    "compare_summary_rows",
    "format_sample_refs_inline",
    "make_check",
    "normalize_failure_reason",
    "prioritize_checks",
    "render_html_sample_refs_inline",
    "render_markdown_failure_clusters",
    "render_markdown_risk_categories",
    "summarize_comparison_delta",
    "top_method_check",
    "top_variant_check",
]
